# Generated by Django 3.1.8 on 2021-07-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('video_id', models.CharField(max_length=100)),
                ('new_comment', models.CharField(max_length=100)),
                ('previous_comment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='comment.comment')),
            ],
        ),
    ]
